### PR TITLE
improve error and warning lists

### PR DESCRIPTION
**Pull request by v4hn**
* sort entries to group them by path
* filter out AnalyzerGroup entries as they do not add additional information

before:
without_patches

after:
with_patches

### CODE REVIEW

**Comment by arne48** [comment]
Thank you very much for this PR.
I think these changes make sense to and the readability would benefit from decluttering the list.
Also the sorting is a good idea.
I will quickly check it and then merge & release it.
BTW would you be willing to also create a PR for the ros2 branch so also ROS2 users can get these improvements?

**Comment by v4hn** [comment]
I tried to cherry-pick and stumbled across #30 . So I had to adjust the patch and decided to just include it #30 as a ROS1 backport in here as well. Hope that's ok, but at the very least now I am confident that the patches actually work together ;) (no ROS2 around here).

**Comment by arne48** [comment]
@v4hn Thank you very much for the additional PR.
Backporting it a was a good idea. :)
I will go through the process over the weekend.

**Comment by arne48** [comment]
@v4hn Thank you very much for your contribution.
The new version 0.5.14 (ros1) and 1.0.5 (ros2) is now on its way being released. :)

**Comment by v4hn** [comment]
thank you! I'd wish some other project maintainers were that responsive for such minor requests... :+1:

**Comment by v4hn** [comment]
sorry to abuse this thread. But seeing how you released this patch quickly, do you feel you could also take care of https://github.com/ros-visualization/rqt/issues/259 and https://github.com/ros-visualization/rqt_tf_tree/issues/36 that are stuck because of the missing releases?

**Comment by arne48** [comment]
I would really like to help you with this @v4hn.
Unfortunately does the release process involve another intermediate package which contains the references to the latest versions and some more house-keeping stuff.
However, only the respective maintainers obtain the permission to push to that package.
For ROS1 it still needs to be done individually on a package by package basis.
ROS2 is a little bit different and I might have been able to help you.
But according to your issues your problem concerns the Noetic release.
Maybe what you could do is opening another Issue referring to the ones you have and ask if they would like to add me (or you) as an additional maintainer. If they accept and after the permissions were updated, the problem could be solved.
I would just rather not interject myself into the release decisions of other maintainers as it is strictly speaking not my business to tell others what to do.
But I am always happy if I can help or support.

Sorry for the long answer but I hope explaining the situation in a more detailed manner was more help full.

Best,
Arne

**Comment by v4hn** [comment]
Thank you for taking the time to write down the explanation. :sunglasses: 
What I read from your reply is that you *could* push to the main repository already. This is funny insofar as I am part of the [ros orphaned project](http://wiki.ros.org/OrphanedPackage) and have push access to the gbp repositories, but not upstream. So if we would work together, you could `catkin_prepare_release` and push and I could bloom. :partying_face: 

But before that I will first create issues asking about whether they could add you as maintainers. :+1:

**Pull request merged**
