### PR TITLE
update urls

### PR DESCRIPTION
**Pull request by dirk-thomas**
With the plugin being split out from `rqt_robot_plugins` I will do a last release for Lunar (as well as re-release for Kinetic, Jade, and Indigo) in the next days. After that I will stop watching this repo, not look at issues and pull requests, and not perform new releases.

Someone needs to take over the maintenance role which specifically includes doing new releases. @trainman419 You are currently listed in the manifest as the maintainer. I am not sure if you want to take this role and fully take over this repository? Or anyone else would like to step up (@ablasdel @arne48 @130s since you have contributed to the package in the past)?

Please let me know if you want to be added / removed from the list of maintainers in the manifest. Otherwise I will go ahead and merge this as-is and release the package a last time setting the maintenance status to `unmaintained`.

### CODE REVIEW

**Comment by arne48** [comment]
Sure, I would like to continue maintaining this plugin after it got split from the other plugins.

**Comment by ablasdel** [comment]
I'll be co-maintainer here.

**Comment by dirk-thomas** [comment]
@arne48 Can you please comment with the maintainer line to be used for you. Just want to make sure I get the info right. I will update this (as well as other) PRs.

**Comment by arne48** [comment]
@dirk-thomas 
<maintainer email="arne.hitzmann@gmail.com">Arne Hitzmann</maintainer>
Thank you for trusting me.

**Comment by dirk-thomas** [comment]
Great! I have [added](ba4278f1df709cafaf01847b1508e0caa9a2e6fe) @ablasdel and @arne48 as maintainers and will move forward with the release.

**Pull request merged**
