### PR TITLE
No copy queue / diagnostic status messages

### LINKED ISSUE #10: Very slow on opening inspector window
Opening an inspector window often slows down or sometimes causes crash of this app.
This happens especially when one aggregated message has many statuses and the pause button is NOT pressed.

### PR DESCRIPTION
**Pull request by furushchev**
This fixes #10.
The original code copies received diagnostic message queues which slows down the program when a message has many statuses.
By applying this PR, no more copy is occured. The issue is now fixed.

### CODE REVIEW

**Comment by arne48** [comment]
Thank you very much for submitting a PR for reducing the computational overhead of copying the data.
Originally this was done because in a case where a lot of messages are processed the status could be changed while it was accessed by another thread. So to avoid locking a copy for the display thread got updated.
If your solution doesn't show a regression to this issue, it would be a nice performance improvement.
I will have a look into it and merge it if it works.

**Comment by arne48** [comment]
As a assumed after a first read of the commits and as it was confirmed by a test, this bug fix reintroduces the "mutated during iteration" bug.
The test included a diagnostic_aggregator, which triggers the bug instantly at a pub_rate of 500 and after a few seconds at 100.

**Traceback (most recent call last):
  File "/home/user/catkin_ws/src/rqt_robot_monitor/src/rqt_robot_monitor/robot_monitor.py", line 169, in queue_updated
    levels = [max([s.level for s in s.values()]) for s in self._timeline]
  File "/home/user/catkin_ws/src/rqt_robot_monitor/src/rqt_robot_monitor/timeline.py", line 179, in __iter__
    for msg in self._queue:
RuntimeError: deque mutated during iteration
Aborted**

I really like the cleanup you did in the code, so if you would address this problem with an additional commit, I would really like to merge it to improve the codebase.

**Comment by furushchev** [comment]
@arne48 Thank you very much for reviewing and testing.
I now confirmed the issue when the publish rate of `diagnostic_agg` is very high, though I think it is a rare case.
I added an additional commit to fix this issue by copying the deque as list on iteration, and now the error disappears on my testing environment.
Besides the issue, I could also see the GUI slows down when a `rqt_robot_monitor` node receives  at very high publish rate.
This occurs because signals to call methods for redrawing GUI are emitted on every call of message callback.
I fixed this issue by ignoring all the queued signals while redrawing is processing.
Could you test if these fixes the issue on your env?
Thanks!

**Comment by arne48** [comment]
Very nice. I will test it and if everything works (what I would expect now on a first glance) I will merge it.
Thank you for your contribution.

**Comment by arne48** [comment]
Thank you very much for your contribution. This also increased the responsiveness of the gui under heavy load.

**Comment by furushchev** [comment]
@arne48 Thank you for further testing and merging! :+1:

**Pull request merged**
