### PR TITLE
The type of the dict key value has been changed to byte because this …

### PR DESCRIPTION
**Pull request by fletzerm**
…is the type used in the diagnostic message.

### CODE REVIEW

**Comment by Karsten1987** [comment]
While I can double click correctly now on the warning fields, the robot monitor crashes when I try to close that window.

**Comment by norro** [comment]
Works for me!

**Comment by fletzerm** [comment]
> While I can double click correctly now on the warning fields, the robot monitor crashes when I try to close that window.

Perhaps this is a different issue? I have the same crash problems with and without these changes.

**Comment by arne48** [comment]
@fletzerm thank you for this fix.
I will also have a look at the issue @Karsten1987 mentioned and then merge both fixes for a new release.

**Comment by arne48** [comment]
After some initial tests, I can confirm that.
a. @fletzerm 's patch solves the color problem
b. the patch introduces a bug @Karsten1987 noticed, where the plugin crashes once you try to close a details window
So I have to withhold this patch, util we (I) found the root cause for the segfault and fixed it.

**Comment by fletzerm** [comment]
I think I have found a solution for this problem. I will provide a patch.

**Comment by arne48** [comment]
Thank you very much @fletzerm.
The problem should be fixed by these patches.

**Pull request merged**
